spring:
  application:
    name: vox

  docker:
    compose:
      enabled: true

  datasource:
    url: jdbc:postgresql://postgres:5432/vox
    username: dev
    password: dev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:/db/migration

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

jwt:
  secret: Ad7xJb49yBZd14ahYm8okUIUJ1FBSOLpMwXiXZ5DcBg=
  expiry: 3600000