ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE users ALTER COLUMN updated_at TYPE TIMESTAMPTZ;
ALTER TABLE rooms ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE messages ALTER COLUMN sent_at TYPE TIMESTAMPTZ;